<a href="https://colab.research.google.com/github/PJHSE/Class2022Spring/blob/main/0317Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
a = np.matrix([[1,2],[3,4],[5,6]])
b = np.array([[1,2],[3,4],[5,6]])
print(a)
print(b)
print(type(a))
type(b)
print('-'*20)
c = np.array([[1,2,3],[4,5,6]]) 
print(c)
d = a*c
print(d)



#A = [1, 2; 3, 4; 5, 6]    #파이썬은 이렇게 안되나?
#A

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.matrix'>
--------------------
[[1 2 3]
 [4 5 6]]
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


array로 행렬 생성했을 때 항등행렬이랑 곱하니 다른 값이 나와버림. 

In [16]:
A = np.matrix([[1.0,2.0],[4.0,5.0]])
B = np.matrix([[1,1],[0,2]])
I = np.eye(2)
print(A)
print(B)
print(I)
print(I*A)
if I*A==A:   #???? 왜 오류?
  print('true')
else:
  print('error')

[[1. 2.]
 [4. 5.]]
[[1 1]
 [0 2]]
[[1. 0.]
 [0. 1.]]
[[1. 2.]
 [4. 5.]]


ValueError: ignored

In [17]:
print(A*B)
print(B*A)

[[ 1.  5.]
 [ 4. 14.]]
[[ 5.  7.]
 [ 8. 10.]]


In [23]:
InvA=np.linalg.inv(A)
print(np.transpose(A))
print(A)

[[1. 4.]
 [2. 5.]]
[[1. 2.]
 [4. 5.]]


In [20]:
print(InvA)

print(A*InvA)

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
[[1.00000000e+00 0.00000000e+00]
 [2.22044605e-16 1.00000000e+00]]


In [24]:
A = np.matrix([[1,-4],[-2,1]])
B = np.matrix([[0,3],[5,8]])

In [25]:
A-B

matrix([[ 1, -7],
        [-7, -7]])

In [26]:
C = np.matrix([[5],[5],[2],[7]])
C

matrix([[5],
        [5],
        [2],
        [7]])

In [27]:
D = 2*C
D

matrix([[10],
        [10],
        [ 4],
        [14]])

In [31]:
E = np.matrix([[1,3,-1]])
F = np.matrix([[2],[2],[4]])
G = E*F

In [32]:
print(G)

[[4]]


ㅇㅁㄴㅇㅁㄴ

In [33]:
def square_return(num):
  return num**2

def square_print(num):
  print(num**2)

In [41]:
answer_return = square_return(4)

def add(number1, number2):
    print(number1 + number2)

result = add(1, 3)
#new_result = result + 1            #왜 에러 뜨는지 알아야 함.

def add(number1, number2):
    return number1 + number2

result = add(1, 3)
new_result = result + 1
new_result                          #이러면 에러가 안뜸 !

def add(number1, number2):
    return number1 + number2
    print("hello")

result = add(1, 3)                  #hello 안나옴!!!!!! return!

def add(number1, number2):
    print(number1 + number2)

result = add(1, 3)                  #여기서 result의 value는 없다는 거 !

4
4


In [42]:
input("what is your name? ")

what is your name? Park


'Park'

In [43]:
name = input("What is your name?")

What is your name?Park


In [44]:
name

'Park'

In [45]:
age = input("How old are you? ")

How old are you? 24


In [47]:
type(age)
age                   #input함수는 str으로 바꾼다. 

'24'

In [48]:
s = '''How
are
you'''
s

'How\nare\nyou'

In [49]:
print('3\t4\t5')

3	4	5


In [50]:
print('\\')

\


In [51]:
print('don\'t do')

don't do


In [52]:
print("this \n is the newline character in Python")

this 
 is the newline character in Python
